aws-powertools/powertools-lambda-java

README.md, docs/content/core/tracing.mdx
Fixing some documentation issues:
- README.md
- Tracing.mdx
**Checklist**
=> docs: fixing documentation

.github/workflows/build-docs.yml, .github/workflows/build.yml, docs/content/core/logging.mdx, docs/content/dummy.md, docs/content/utilities/sqs_large_message_handling.mdx
Optimise build process
**Checklist**
=> ci: Build docs action update

docs/content/utilities/sqs_large_message_handling.mdx, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/PowertoolsSqs.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageAspect.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/PowertoolsSqsTest.java
Utility method to fetch large payload from S3 for SQS messages without needing to use annotation and have more control over failures.
**Checklist**
=> feat: Utility without annotation

.github/ISSUE_TEMPLATE/bug_report.md, docs/content/core/tracing.mdx, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-logging/src/main/java/org/apache/logging/log4j/core/layout/LambdaJsonLayout.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/PowertoolsLogging.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/LambdaHandlerApiGateway.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/PowertoolsTracing.java
Changes:
* Fix some of the markdown used
* Removed unused imports
* LambdaHandlerProcessor - Make null check easier to read
* LambdaJsonLayout - Remove unused objectMapper
* Fix typos
**Checklist**
=> fix(general): clean up typos and code

README.md, docs/content/index.mdx
=> docs: Update docs to reflect about metrics coming soon

README.md, example/template.yaml
Improvements to read me.
- Remove feature setup instruction from readme since its present on documentation site.
- Refer to example application in readme.
**Checklist**
=> docs: Readme update

.github/workflows/build.yml, docs/content/core/metrics.mdx, docs/gatsby-config.js, example/HelloWorldFunction/pom.xml, example/HelloWorldFunction/src/main/java/helloworld/App.java, example/HelloWorldFunction/src/main/java/helloworld/AppStream.java, pom.xml, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java, powertools-metrics/pom.xml, powertools-metrics/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricsLoggerHelper.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/PowertoolsMetrics.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/PowertoolsMetricsLogger.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/ValidationException.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/PowertoolsMetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsColdStartEnabledHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledStreamHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsExceptionWhenNoMetricsHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsNoDimensionsHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsNoExceptionWhenNoMetricsHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsTooManyDimensionsHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java
EMF logging support
**Checklist**
=> feat: Metrics utility

README.md, docs/content/core/metrics.mdx
Fixes to the readme and formatting of the metrics doc page.
**Checklist**
=> docs: fixes to the documentation

powertools-tracing/pom.xml
Removing the unused Log4J dependencies from the tracing module.
**Checklist**
=> fix: Removing Log4J dependencies from the tracing module.

README.md, docs/content/index.mdx, docs/content/utilities/sqs_large_message_handling.mdx, example/HelloWorldFunction/pom.xml, pom.xml, powertools-core/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-sqs/pom.xml, powertools-tracing/pom.xml
=> ci: preparing release v0.3.1-beta

docs/content/core/logging.mdx, powertools-logging/pom.xml, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/SystemWrapper.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java
Closes #88 
Integration with CloudWatch ServiceLens:
The xray_trace_id key is added to log output when tracing is active. This enables the log correlation functionality in ServiceLens to work with applications using powertools.
**Checklist**
=> feat: integration with CloudWatch ServiceLens #88

README.md, docs/content/index.mdx, docs/content/utilities/parameters.mdx, docs/content/utilities/sqs_large_message_handling.mdx, example/HelloWorldFunction/pom.xml, pom.xml, powertools-core/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-sqs/pom.xml, powertools-tracing/pom.xml
=> ci: Prepare for 0.4.0-beta

pom.xml, powertools-logging/pom.xml
Fixes warning like below:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
-- | --
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
=> fix: Make slf4j work along with log4j2

example/README.md
Gradle install url is at https://gradle.org/install/
**Checklist**
=> fix(docs): Correct url and notes for gradle

.github/workflows/build.yml, docs/content/utilities/validation.mdx, example/HelloWorldFunction/src/main/java/helloworld/AppValidation.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationConfig.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/Base64FunctionTest.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/Base64GZipFunctionTest.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ValidationAspectTest.java
=> refactor: Rename helpers for validation module

powertools-parameters/pom.xml, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java
Closes #181 
Also https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/
**Checklist**
=> perf: Make UrlConnectionHttpClient default client for params fetch

.github/workflows/build-docs.yml, .github/workflows/docs.yml, docs/content/index.mdx, example/HelloWorldFunction/build.gradle, example/HelloWorldFunction/pom.xml, example/template.yaml, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
=> chore: upgrade AspectjGradlePlugin to latest  and example project to java 11

docs/content/index.mdx, docs/src/gatsby-theme-apollo-docs/components/page-content.js
=> Docs update

docs/src/gatsby-theme-apollo-docs/components/page-content.js
Adds Source code URL in the side bar to keep in sync with Python docs ;)
**Checklist**
=> docs: add source code link in nav bar

docs/src/gatsby-theme-apollo-docs/components/multi-code-block.js, docs/src/gatsby-theme-apollo-docs/components/page-layout.js, docs/src/gatsby-theme-apollo-docs/components/select.js, docs/src/gatsby-theme-apollo-docs/prism.less
This will keep the side bar menu always expanded
**Checklist**
=> docs: shadow sidebar to remain expanded

powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspect.java
replace Apache Commons Logging with SLF4J
Apache Commons Logging is an obsolete library and should not be used in
modern Java systems.
**Checklist**
=> refactor: replace Apache Commons Logging with SLF4J

.github/workflows/build.yml
add JDK 15 to CI build matrix
https://jdk.java.net/15/
**Checklist**
=>  ci: add JDK 15 to build matrix

docs/content/core/tracing.mdx, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/Tracing.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/nonhandler/PowerToolNonHandler.java
* add segmentName attribute to Trace annotation
* if segmentName is provided, use it as subsegment name instead of traced
method's name
**Checklist**
=> feat: custom segment names

docs/content/core/tracing.mdx, docs/content/index.mdx, powertools-tracing/pom.xml, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/CaptureMode.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/Tracing.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/SystemWrapper.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledExplicitlyForResponseAndError.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledForError.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledForResponse.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledForStreamWithNoMetaData.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledWithNoMetaDataDeprecated.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
=> feat: support for env variable in tracing capture modes

docs/content/core/tracing.mdx, docs/content/index.mdx, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/CaptureMode.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
=> chore: Consistent env variable names for tracing

.github/workflows/build.yml, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsWithExceptionInHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
**Issue #285 
capture metrics even when handler results in exception
**Checklist**
=> feat: capture metrics even when handler results in exception

powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
https://github.com/awslabs/aws-lambda-powertools-java/issues/297
Fix for point 2.
AwsRequestId is now added to each EMF log output.
**Checklist**
=> Issue 297: Add AwsRequestId to each EMF log.

powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/LoggingUtils.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/handlers/PowerToolLogEventEnabledWithCustomMapper.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java, powertools-logging/src/test/resources/customizedLogEvent.json
**Issue #275 and #66
Ability to override default object mapper used for serialization while logging received event. This can also be used to control what is logged from event based on the configuration of object mapper. Refer [PowerToolLogEventEnabledWithCustomMapper.java ](https://github.com/awslabs/aws-lambda-powertools-java/compare/override-object-mapper?expand=1#diff-2cbe80bce7fa67f977ebe28b0c9c0470d77b2b4b426df42bce658dce5456bd1c)
**Checklist**
=> feat: ability to override object mapper used for logging event

powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/SystemWrapper.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java, powertools-metrics/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricsLoggerHelper.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
**Issue #297 
Expose another helper utility method to pick default namespace from top level annotation or env var
**Checklist**
=> feat: single metric utility method to pick default namespace

docs/content/core/logging.mdx
Doc updates for https://github.com/awslabs/aws-lambda-powertools-java/pull/302
**Checklist**
=> docs: ability to override object mapper used for logging event

docs/content/core/logging.mdx, docs/content/index.mdx, example/template.yaml, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
**Issue #293 
**Checklist**
**RFC issue #
=> fix: powertools specific log level env var to not conflict with the system LOG_LEVEL

powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
=> chore: consistent field names for trace and req id with logger

docs/core/metrics.md, docs/index.md, docs/utilities/batch.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledDefaultDimensionHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsNoDimensionsHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
**Issue #297 #320 
Powertools wont capture default dimesion emitted via emf library. By default, it emits following dimensions `"Dimensions":[["LogGroup","ServiceName","ServiceType","Service"]]`.
Now in sync with python version, it will by default emit only `Service`dimension
**Checklist**
=> feat: Default dimensions from powertools instead of emf library 

.github/workflows/build-docs.yml, docs/core/metrics.md, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledDefaultDimensionHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledDefaultNoDimensionHandler.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
=> Mertics default dimensions

.github/workflows/auto-merge.yml, .github/workflows/build.yml
Auto merge of PRs are failing due to recent change in how Github treats dependabot PRs 
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
**Checklist**
=> chore: fix auto merge dependabot PR

powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/Tracing.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledWithNoMetaDataDeprecated.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
Reverts awslabs/aws-lambda-powertools-java#330
We will target removal of deprecated attributes as a separate major release. Ref discussion here https://github.com/awslabs/aws-lambda-powertools-java/pull/345
=> Revert "feat: remove deprecated attributes on Tracing annotation"

CHANGELOG.md, README.md, docs/index.md, docs/utilities/batch.md, docs/utilities/parameters.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md, example/HelloWorldFunction/build.gradle, example/HelloWorldFunction/pom.xml, pom.xml, powertools-core/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-sqs/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
=> chore: prep release 1.5.0

.github/workflows/build.yml, .github/workflows/publish.yml
setup-java version 2
https://github.com/actions/setup-java/blob/main/README.md
**Checklist**
=> core: setup-java v2

docs/core/logging.md, docs/utilities/sqs_large_message_handling.md, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/LoggingUtils.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/LoggingUtilsTest.java
**Issue #, if available:** #394 
closes #394 
**Checklist**
=> feat: logger-Remove custom keys interface

powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/TracingUtilsTest.java
#421 
Updated `TracingUtils` and corresponding test
**Checklist**
=> feat: #421 Support for Boolean and Number type as value in TracingUtils putAnnotation

powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/LoggingUtils.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
=> chore: Logging and SQS utility Optimisations

README.md, docs/index.md, docs/utilities/batch.md, docs/utilities/parameters.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md, example/HelloWorldFunction/pom.xml, pom.xml
**Issue #, if available:**  https://github.com/awslabs/aws-lambda-powertools-java/issues/50
**Checklist**
=> chore: Upgrade to latest(1.14.0) aspectj-maven-plugin

powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsBatch.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspect.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsBatchProcessorTest.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsMessageHandlerWithNonRetryableHandler.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsMessageHandlerWithNonRetryableHandlerWithDelete.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java, powertools-sqs/src/test/resources/threeMessageSqsBatchEvent.json
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/29
**Checklist**
=> feat(batch-processing): move non retry-able message to DLQ

docs/utilities/batch.md
=> docs(batch-processing): Support for moving non retryable msg to DLQ

.github/workflows/spotbugs.yml, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SQSBatchProcessingException.java
=> chore: spotbug check

docs/utilities/sqs_large_message_handling.md, powertools-sqs/pom.xml, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspect.java, powertools-sqs/src/main/java/software/amazon/payloadoffloading/PayloadS3Pointer.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsLargeMessageTest.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspectTest.java, powertools-test-suite/src/test/java/software/amazon/lambda/powertools/testsuite/LoggingOrderTest.java, spotbugs-exclude.xml
=> feat(sqs:large-message): Expose SDK v2 s3 client

docs/index.md, mkdocs.yml
Syncing changes as per https://github.com/awslabs/aws-lambda-powertools-python/pull/823
**Checklist**
=> docs(tenets): update Idiomatic tenet to Progressive

docs/index.md, example/HelloWorldFunction/build.gradle
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-java/issues/146
**Checklist**
=> chore: Update docs to reflect latest gradle plugin fix

powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsBatchProcessorTest.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java, powertools-sqs/src/test/resources/sampleSqsBatchEventBatchSize25.json
**Issue #, if available:** #663
**Checklist**
=> fix: support batch size greater than 10 processing

docs/index.md, docs/utilities/batch.md, docs/utilities/custom_resources.md, docs/utilities/parameters.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-java/issues/146
Update docs to use [freefair gradle plugin for aspectj](https://docs.freefair.io/gradle-plugins/5.0.1/reference/#_io_freefair_aspectj_post_compile_weaving). The plugin is actively maintained and works on all gradle versions like 5, 6 and 7
**Checklist**
=> chore(docs): use free fair gradle aspect plugin

docs/FAQs.md, mkdocs.yml
https://github.com/awslabs/aws-lambda-powertools-java/issues/630
Added new section for FAQs (intended as a page with usefull for users information that are not related to other sections) 
**Checklist**
=> chore(docs): Add FAQs section to docs with information about Lombok support.

.github/workflows/release-prep.yml, docs/Dockerfile, docs/index.md, docs/utilities/batch.md, docs/utilities/custom_resources.md, docs/utilities/parameters.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md, mkdocs.yml
With this change, release preparation process is mostly automated.  It will bump the version to the specified version while running workflow dispatch action and specifying the version. 
It will also create a placeholder in changelog to update. This is the part which needs to be updated manually via person who is supposed to make a release.
Sample automated PR generated https://github.com/awslabs/aws-lambda-powertools-java/pull/695
**Checklist**
=> chore: Automate release prep

docs/core/tracing.md, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledForResponseWithCustomMapper.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java, spotbugs-exclude.xml
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-java/issues/673
**Checklist**
=> feat(tracing): ability to override object mapper

docs/index.md, example/HelloWorldFunction/build.gradle, example/HelloWorldFunction/gradle/wrapper/gradle-wrapper.properties, example/HelloWorldFunction/pom.xml
closes #702
Changes:
- Bump gradle version to 7.3.3
- Use `io.freefair.aspectj.post-compile-weaving` in example project
- Specify java 11 for sourceCompatibility, targetCompatibility
- Bump junit version to 4.13.2
closes #702
**Checklist**
=> fix(gradle): Fix gradle example and docs to work with java 12+

docs/utilities/batch.md, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java, powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java
**Issue** https://github.com/awslabs/aws-lambda-powertools-java/issues/729
**Checklist**
=> fix: Prevent message to be marked as success if failed sending to DLQ

docs/core/tracing.md
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-java/issues/727
Cookie cutter project is updated as well to use the recommended configuration.
**Checklist**
=> chore(docs): Clarify test config needed for Tracing module

docs/utilities/custom_resources.md
There is a rendering issue with the docs for custom resources
Fix the formatting of the header info
**Checklist**
=> fix(docs): fix title for custom resources page

README.md, docs/index.md, mkdocs.yml, pom.xml, powertools-cloudformation/pom.xml, powertools-core/pom.xml, powertools-idempotency/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-sqs/pom.xml, powertools-test-suite/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
**Issue #, if available: #779**
Searched through repo to find instances of project name being any of the following:
- AWS Lambda Powertools (Java)
- Lambda Powertools Java
- AWS Lambda Powertools Java
Changed each instance to "AWS Lambda Powertools for Java".
**Checklist**
=> Documentation: Changed project name for consistency

docs/index.md
There was one more existence of project name that needs to be renamed. 
**Checklist**
=> chore(docs): additional rename of project name (#781)

powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotentAspect.java, powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java, powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStoreTest.java
When disabling idempotency using the environment variable "`POWERTOOLS_IDEMPOTENCY_DISABLED`", the creation of the `DynamoDbClient` was not disabled, which is not desired when performing tests (it tries to connect to AWS or requires to setup a local dynamodb)
When using the "`POWERTOOLS_IDEMPOTENCY_DISABLED`" env var, the `DynamoDbClient` (for the idempotency module) is not created.
**Checklist**
=> fix: disable idempotency doesn't disable dynamodb client creation in persistent store

powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStore.java
[**Issue #, if available:**](https://github.com/awslabs/aws-lambda-powertools-java/issues/816)
Making MessageDigest thread-safe
**Checklist**
=> Fixed thread-safety issue of MessageDigest

CHANGELOG.md, README.md, mkdocs.yml, pom.xml, powertools-cloudformation/pom.xml, powertools-core/pom.xml, powertools-idempotency/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-sqs/pom.xml, powertools-test-suite/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
https://github.com/awslabs/aws-lambda-powertools-java/issues/919
**Checklist**
Upgraded version of X-Ray library to resolve vulnerable transitive dependencies.
=> chore:Prep release 1.12.3

.github/ISSUE_TEMPLATE/support_powertools.yml
n/a
This marks a new milestone where we can accept public references via GitHub 🎉
**Checklist**
=> docs(governance): new form to allow customers self-nominate as public reference

powertools-validation/pom.xml, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/SQSWithCustomEnvelopeHandler.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/SQSWithWrongEnvelopeHandler.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ValidationAspectTest.java, powertools-validation/src/test/resources/sqs_message.json
**Issue #, if available:** #959
When an envelope is set, it takes precedence over the built-in types. If not set, built-in types validation apply. If the type is not handled, a warn is logged.
**Checklist**
People using an envelope with a built-in type (useless) may now enter in the envelope validation rather than the built-in one, causing validation error.
=> fix: envelope is not taken into account with built-in types

powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/cache/DataStore.java, powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java
This is a fix for PR https://github.com/awslabs/aws-lambda-powertools-java/pull/577:
- rebase to fix issue with mocking Random
- some changes in caching json schema logic
=> Fix for #577: Some code suggestion from CodeGuru 

powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
**Issue #, if available:** #945
`SqsLargeMessageAspect` is not necessarily in the classpath, which cause an issue (warning during compilation) with gradle
- remove SqsLargeMessageAspect in DeclarePrecedence in Logging Module:
- The * before `LambdaLoggingAspect` includes `SqsLargeMessageAspect`
**Checklist**
* [] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [] Update tests
* [] Update docs
=> fix: compilation warning with SqsLargeMessageAspect on gradle

CHANGELOG.md, README.md, mkdocs.yml, pom.xml, powertools-cloudformation/pom.xml, powertools-core/pom.xml, powertools-idempotency/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-sqs/pom.xml, powertools-test-suite/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
=> chore: update the project version to 1.13.0

README.md, docs/index.md
Add information about Pyton, Typescript and .Net implementation of PowerTools 
**Checklist**
=> Add information about other supported languages to README and docs.

.github/dependabot.yml, pom.xml
Bump manually Mockito to latest supported version (4.11.0).
Configure dependabot to avoid bumping Mockito to v. 5 as it requires Java 11.
---------
**Checklist**
=> Bump Mockito to latest compatible version.

docs/core/metrics.md, powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
closes #999
**Issue #, if available:** #999
introduce new `MetricsUtils.withMetricsLogger` utility method to enable higher level of customization to the metrics logger and eliminate the need to know the metric/configuration when calling the method and leave that instead to the `Consumer<MetricsLogger>`
The main use case my team has
1. We're emitting a number of metrics - ~10 metrics - that all have the same config (e.g. dimensions) that's meant to be different from `MetricsUtils.metricsLogger()` i.e. we need a new metrics logger instance
2. The names of those metrics are generated dynamically - think loops, appending different constants - to generate those names
So, ideally, we create a new instance of a metrics logger, and then rely on to emit those 10 different metrics.
**Checklist** …
=> feat(metrics): introduce  MetricsUtils.withMetricsLogger utility

.github/workflows/build.yml, README.md, examples/pom.xml, examples/powertools-examples-validation/pom.xml, pom.xml
**Issue #, if available:** #1080
- removed cobertura as we have also jacoco
- merge results in parent target folder
**Checklist**
=> maintenance: send coverage (jacoco) to codecov

docs/utilities/custom_resources.md
**Issue #, if available:** https://github.com/awslabs/aws-lambda-powertools-java/issues/1081
Improving the Cloudformation custom resources documentation, including the new APIs introduced as part of this PR https://github.com/awslabs/aws-lambda-powertools-java/pull/1082
**Checklist**
=> docs(cloudformation-module): Improve Docs

CHANGELOG.md, README.md, examples/pom.xml, examples/powertools-examples-core/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-parameters/pom.xml, examples/powertools-examples-serialization/pom.xml, examples/powertools-examples-sqs/pom.xml, examples/powertools-examples-validation/pom.xml, mkdocs.yml, pom.xml, powertools-cloudformation/pom.xml, powertools-core/pom.xml, powertools-idempotency/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-sqs/pom.xml, powertools-test-suite/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
Release preparation: update the project version to 1.15.0
**Checklist**
=> chore: update the project version to 1.15.0

docs/utilities/validation.md
Fix goupId of Maven dependency
The `<groupId>` in the Maven example isn't correct and doesn't match the `<groupId>` in the `<plugin><aspectLibraries>`.  Checking Maven Central, I've confirmed that `<groupId> software.amazon.lambda</groupId>` is the correct group.  This PR is to fix the errant dependency.
**Checklist**
=> docs:  update groupId in Maven dependency of powertools-validation

README.md, docs/index.md, docs/utilities/batch.md, docs/utilities/idempotency.md, docs/utilities/parameters.md, docs/utilities/sqs_large_message_handling.md, docs/utilities/validation.md, examples/powertools-examples-core/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-parameters/pom.xml, examples/powertools-examples-sqs/pom.xml, examples/powertools-examples-validation/pom.xml, pom.xml, powertools-e2e-tests/handlers/idempotency/pom.xml, powertools-e2e-tests/handlers/logging/pom.xml, powertools-e2e-tests/handlers/metrics/pom.xml, powertools-e2e-tests/handlers/pom.xml, powertools-e2e-tests/handlers/tracing/pom.xml, powertools-serialization/pom.xml, powertools-test-suite/pom.xml
**Issue #:** https://github.com/awslabs/aws-lambda-powertools-java/issues/1156
According to https://github.com/mojohaus/aspectj-maven-plugin/issues/154 this plugin should be swapped with [dev-aspectj plugin](https://github.com/dev-aspectj/aspectj-maven-plugin), which works with Java 17 project.
This PR updates the repo, examples and docs to use the new plugin.
**Checklist**
=> chore: Swap implementation of `aspectj-maven-plugin` to support Java 17

.github/workflows/docs.yml
**Issue #, if available:** #1212
Remove GH pages from GH actions. We no longer use GH pages, as we have migrated to our new docs hosting already.
**Checklist**
=> fix: remove GH pages

.github/workflows/build.yml
Change the github build workflow to use corretto and build with all Java versions from 8 to 20.
**Checklist**
=> chore: add all java versions and use corretto for build

.github/workflows/run-e2e-tests.yml, pom.xml, powertools-e2e-tests/pom.xml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/IdempotencyE2ET.java
Run end-to-end tests with GitHub actions. 
**Checklist**
=> chore: E2E tests GitHub action

.github/dependabot.yml
Reason: Mockito 5 requires Java 11.  Issue with incorrect name found after the migration. 
=> Fix Dependabot configuration to ignore latest version of Mockito

.github/workflows/run-e2e-tests.yml, powertools-e2e-tests/handlers/parameters/pom.xml, powertools-e2e-tests/handlers/parameters/src/main/java/software/amazon/lambda/powertools/e2e/Function.java, powertools-e2e-tests/handlers/pom.xml, powertools-e2e-tests/pom.xml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ParametersE2ET.java
Fix end to end tests for Java8. Error due to aspectJ version 
**Checklist**
=> fix: e2e tests on JDK8

docs/index.md, docs/javascript/extra.js, examples/powertools-examples-core/template.yaml, examples/powertools-examples-sqs/template.yaml, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/AppConfigProvider.java
**Issue #, if available:** #1237
Update base origin variable in mkdocs javascript
Change `awslabs.github.io` to `docs.powertools.aws.dev`
**Checklist**
=> chore: Update docs base origin url

.github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/run-e2e-tests.yml, pom.xml
profile 'without-spotbugs' is misleading and should be the default, and use 'with-spotbugs' when we want to run spotbugs check.
➡️ remove `build-without-spotbugs` profile
➡️ clean `build-with-spotbugs` that contains javadoc and source which should not be there
➡️ move the javadoc and source generation in the release profile (only needed at this stage to publish them on mvn central)
**Checklist**
=> chore: cleanup spotbugs maven profiles

examples/powertools-examples-core/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-parameters/pom.xml, examples/powertools-examples-serialization/pom.xml, examples/powertools-examples-sqs/pom.xml, examples/powertools-examples-validation/pom.xml
The last deploy to maven central successfully deployed, but failed the overall build when it got to the examples and tried and failed to deploy them. This disables deploy for each of them - examples don't belong in maven central. 
**Checklist**
=> fix: examples shouldn't be deployed to mvn central

powertools-parameters/pom.xml, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/ParamManager.java, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java, powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java, powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/ParamManagerTest.java
**Issue #, if available:** #1280
- It was partially fixed in https://github.com/aws-powertools/powertools-lambda-java/commit/c7aedc4d2a61013450bf472bb7a8285f8cf80e41 with the addition of constructors with no client in parameter
- Completed the fix, adding the creation of the Client
- Deprecated the generic method to get Providers by passing a class (will be removed in V2)
**Checklist**
=> fix: ParamManager cannot provide default SSM & Secrets providers

CHANGELOG.md, README.md, examples/pom.xml, examples/powertools-examples-cloudformation/pom.xml, examples/powertools-examples-core/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-parameters/pom.xml, examples/powertools-examples-serialization/pom.xml, examples/powertools-examples-sqs/pom.xml, examples/powertools-examples-validation/pom.xml, mkdocs.yml, pom.xml, powertools-cloudformation/pom.xml, powertools-core/pom.xml, powertools-e2e-tests/handlers/pom.xml, powertools-e2e-tests/pom.xml, powertools-idempotency/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-sqs/pom.xml, powertools-test-suite/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/aws-powertools/powertools-lambda-java/blob/prep-release-1.16.1/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
=> chore:Prep release 1.16.1

README.md
Lining our README contents up with the other powertools languages and providing a link to discord. 
**Checklist**
=> docs: Add discord + sec disclosure links to readme

docs/core/logging.md, examples/powertools-examples-parameters/src/main/java/org/demo/parameters/ParametersFunction.java, powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/handlers/IdempotencyFunction.java
**Issue #, if available:** #825
In this change the documentation has been updated to explicitly state the class for which a logger needs to be retrieved.
Also changed two function handler classes to follow this best practice. 
**Checklist**
=> chore: Make request for Logger explicitly for current class

.github/workflows/build-docs.yml, .github/workflows/build.yml, .github/workflows/run-e2e-tests.yml, .github/workflows/spotbugs.yml
#1337 
The v2 branch should build as part of the various build workflows, so that when we PR into it, we can treat it like another 'main'.
**Checklist**
=> chore: Add 'v2' branch to build workflows

examples/powertools-examples-core/cdk/infra/pom.xml
**Issue #, if available:** n/a
The new CDK example infrastructure needs to be blocked from the maven artifact publishing.
**Checklist**
=> fix: Don't deploy the CDK

README.md
#1336 
Update the link to the examples to point at the latest tagged release. The release prep process will move this to the next tag version whenever we deploy a new release.
**Checklist**
=> docs: Change link to absolute versioned path for examples

docs/core/logging.md
Correct logging JSON example shown near bottom of docs.  Still shows `lambda_request_id` - see online [here](https://docs.powertools.aws.dev/lambda/java/core/logging/#setting-a-correlation-id).
This PR updates this example (and others) to `function_request_id`, which aligns with the implementation [here](https://github.com/aws-powertools/powertools-lambda-java/blob/c6932aeb0d0d5689f1c8a5d0f3897c8c69850c3b/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/DefaultLambdaFields.java#L26)
**Checklist**
=> docs(logging): correct log example keys 

powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStore.java, powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
**Issue #, if available:** #1419
Changed the implementation of `BasePersistenceStore#isMissingIdemPotencyKey()` to iterate over elements instead of fields.
**Checklist**
=> fix: array jmespath fail in idempotency module

.github/workflows/build.yml, .github/workflows/pr_artifacts_size.yml, .github/workflows/pr_build.yml, pom.xml
**Issue #, if available:** #1102 
Display a report in GitHub comments about jars size. (Ideally would be great to have the history and see if it's growing)
**Checklist**
=> chore: Reporting size of the jars in GitHub comments

docs/stylesheets/extra.css
**Issue #, if available:** #1452
This PR fixes the hard to read line highlight in dark mode. We had similar issue in [TypeScript before ](https://github.com/aws-powertools/powertools-lambda-typescript/pull/1695/files) and thanks to @shdq he noticed the same problem in Java docs. 
Before: 
After: 
**Checklist**
=> docs: apply line highlight only for default light mode

powertools-validation/src/main/resources/schemas/meta_schema_V201909, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java
=> fix: Fix schema validation unit test build issues

powertools-serialization/pom.xml
**Issue #, if available:** #1471
Enforcing our version of jackson databind to avoid the transitive old one from jmespath
**Checklist**
=> fix: enforce jackson databind version

powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaConstants.java, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java, powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/SystemWrapper.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LoggingE2ET.java, powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1501
If the `_X_AMZN_TRACE_ID` env var is not set, check the `com.amazonaws.xray.traceHeader` system property.
**Checklist**
=> fix: get trace id from system property when env var is not set

examples/powertools-examples-idempotency/pom.xml
**Issue #1255**
Removed dynamodb local from examples directory. 
Idempotency module already contains the dynamodb local version increment. 
Tested with Java 8 and 17 and builds and passes tests locally. 
**Checklist**
=> chore: removing dynamodb local from examples

powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
**Issue #, if available:** #1500
- fallback to default `aws-embedded-metrics` when POWERTOOLS_METRICS_NAMESPACE is not defined.
**Checklist**
=> fix: null namespace should fallback to default namespace

powertools-tracing/pom.xml, powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java, powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/TracingUtilsTest.java
[**Issue #, 1499:**](https://github.com/aws-powertools/powertools-lambda-java/issues/1499)
Change to emit warning log message if an invalid key is used while putting an annotation while tracing.  
**Checklist**
=> chore: Addition of Warn Message If Invalid Annotation Key While Tracing #1511

powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageIdempotentE2ET.java
n/a
The test fails intermittently. If you look at the state of the world after the test fails, the data it is looking for in the DynamoDB table is there. This indicates that the test is failing because we are not giving the Lambda enough time to complete.
Bumping out timing magic numbers is not very satisfying but I can't see another way of doing this.
**Checklist**
=> fix: LargeMessageIdempotentE2ET Flaky 

.github/workflows/run-e2e-tests.yml, README.md, docs/index.md, powertools-e2e-tests/pom.xml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/JavaRuntime.java
Add support for Java 21 in end-to-end tests.
**Checklist**
=> test: e2e tests with java 21

docs/core/logging.md
improve documentation for ALC
**Checklist**
=> docs: update doc for ALC

README.md, docs/index.md, pom.xml, powertools-e2e-tests/handlers/logging/pom.xml, powertools-e2e-tests/handlers/pom.xml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
Do not merge! This is just here to see if the E2E tests run on github.
**Checklist**
=> chore: Testing java21 aspectj pre-release

.github/workflows/run-e2e-tests.yml
n/a
We missed removing some cruft from the Java21/Java17 JDK selection introduced in #1517 in the PR #1519. Remove it!
**Checklist**
=> chore: fix build configuration

.github/workflows/pr_artifacts_size.yml, .github/workflows/run-e2e-tests.yml
do not build examples with Java 8
**Checklist**
=> chore: fix end 2 end build

.github/workflows/pr_build.yml, .github/workflows/pr_iac_lint.yml
=> chore: SAM and Terraform IaC extracted from pr_build and simplified approach.

examples/pom.xml, examples/powertools-examples-batch/pom.xml, examples/powertools-examples-cloudformation/pom.xml, examples/powertools-examples-core-utilities/cdk/app/pom.xml, examples/powertools-examples-core-utilities/cdk/infra/pom.xml, examples/powertools-examples-core-utilities/terraform/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-parameters/pom.xml, examples/powertools-examples-serialization/pom.xml, examples/powertools-examples-validation/pom.xml, pom.xml, powertools-cloudformation/pom.xml, powertools-common/pom.xml, powertools-e2e-tests/pom.xml, powertools-idempotency/pom.xml, powertools-large-messages/pom.xml, powertools-logging/pom.xml, powertools-metrics/pom.xml, powertools-parameters/pom.xml, powertools-serialization/pom.xml, powertools-tracing/pom.xml, powertools-validation/pom.xml, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java
**Issue #**: #1463
Removed duplicated information from child poms that was present in parent pom. 
Added version of plugin and optimised imports to reduce warning noises
**Checklist**
=> chore: cleanup poms and reduce warning noise

examples/powertools-examples-parameters/src/main/resources/log4j2.xml, examples/powertools-examples-serialization/src/main/resources/log4j2.xml, powertools-tracing/src/test/resources/log4j2.xml
[issue](https://github.com/aws-powertools/powertools-lambda-java/issues/1543)
Replaced the LambdaJsonLayout with JsonTemplateLayout as mentioned [powertools-lambda-java/docs/core/logging.md](https://github.com/aws-powertools/powertools-lambda-java/blob/fb14bcfee1aae8e03b8c8081b2478edefc9b5b87/docs/core/logging.md?plain=1#L211-L215)
The log4j2.xml for couple of examples is changed as they were missed earlier.
**Checklist**
=> fix(v2): Removing LambdaJsonLayout from logging config in examples

.github/dependabot.yml
Enable dependabot on v2 branch
**Checklist**
=> chore: dependabot on v2 branch

powertools-parameters/pom.xml, powertools-parameters/powertools-parameters-appconfig/src/main/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigProviderBuilder.java, powertools-parameters/powertools-parameters-appconfig/src/test/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigProviderTest.java, powertools-parameters/powertools-parameters-dynamodb/src/main/java/software/amazon/lambda/powertools/parameters/dynamodb/DynamoDbProviderBuilder.java, powertools-parameters/powertools-parameters-dynamodb/src/test/java/software/amazon/lambda/powertools/parameters/dynamodb/DynamoDbProviderTest.java, powertools-parameters/powertools-parameters-secrets/src/main/java/software/amazon/lambda/powertools/parameters/secrets/SecretsProviderBuilder.java, powertools-parameters/powertools-parameters-secrets/src/test/java/software/amazon/lambda/powertools/parameters/secrets/SecretsProviderTest.java, powertools-parameters/powertools-parameters-ssm/src/main/java/software/amazon/lambda/powertools/parameters/ssm/SSMProviderBuilder.java, powertools-parameters/powertools-parameters-ssm/src/test/java/software/amazon/lambda/powertools/parameters/ssm/SSMProviderTest.java
[issue](https://github.com/aws-powertools/powertools-lambda-java/issues/1544)
Add default transformation manager in params builders
**Checklist**
=> fix(v2): Fix params builder to provide default transformation manager

pom.xml
https://github.com/aws-powertools/powertools-lambda-java/issues/1538
Update dversions 
Jackson to 2.16.0 and 
AWS Xray to 2.15.0
**Checklist**
* [X ] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)
The issue description says these could be breaking changes. 
I did not see any compile errors or breaking unit tests after updating maven dependencies locally on v2 branch.
=> build(deps): bump com.fasterxml.jackson from 2.15.3 to 2.16.0 and com.amazonaws.xray from 2.14.0 to 2.15.0

.github/workflows/pr_build.yml
Remove unecessary credentials acquisition in `pr_build.yaml`.
**Checklist**
=> chore: Fix integration tests

.github/workflows/pr_build_v2.yml, .github/workflows/publish.yml, .github/workflows/run-e2e-tests-v2.yml
**Issue #, if available:** #1523
Remove java 8 builds for pr and e2e tests github actions in v2.
**Checklist**
not yet a breaking change (just the github actions)
**RFC issue #**:  #1523
=> feat(build): remove java 8 support in v2

docs/FAQs.md, docs/utilities/batch.md, docs/utilities/large_messages.md, docs/utilities/parameters.md
**Issue #, if available:** #1092
- Added documentation for using the aws-crt-client with powertools (v2).
- Fixed some documentation issues with typos and code blocks.
**Checklist**
=> chore(v2): document use of aws-crt-client (#1092)

mkdocs.yml
**Issue #, if available:** #1640
This PR adds a link to the Powertools for AWS Lambda workshop in the documentation sidebar. This will allow customers to know about the existence of the workshop.
**Checklist**
=> docs: add link to Powertools for AWS Lambda workshop

.github/workflows/docs-v2-snapshot.yml, .github/workflows/publish-v2-snapshot.yml, .github/workflows/publish.yml, docs/index.md, examples/powertools-examples-core-utilities/sam/pom.xml, examples/powertools-examples-core-utilities/serverless/pom.xml, mkdocs.yml, pom.xml, powertools-idempotency/powertools-idempotency-dynamodb/dynamodb-local-metadata.json, spotbugs-exclude.xml
=> feat(v2): publish snapshots

docs/utilities/validation.md, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationALBE2ET.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationApiGWE2ET.java, powertools-validation/pom.xml, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationConfig.java, powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java, powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java, powertools-validation/src/test/resources/schema_v7.json, powertools-validation/src/test/resources/schema_v7_ko.json
**Issue #, if available:** #1663
Upgrades com.networknt:json-schema-validator to 1.4.3.
Note that the validation error messages have changed since 1.0.87.
```json
{
"validationErrors": [
{
"type": "enum",
"code": "1008",
"message": "/properties/name/type: does not have a value in the enumeration [array, boolean, integer, null, number, object, string]",
"instanceLocation": "/properties/name/type",
"evaluationPath": "/properties/properties/additionalProperties/$ref/properties/type/anyOf/0/$ref/enum",
"schemaLocation": "http://json-schema.org/draft-07/schema#/definitions/simpleTypes/enum",
"messageKey": "enum",
"arguments": [
"[array, boolean, integer, null, number, object, string]"
]
},
{
"type": "type",
"code": "1029",
"message": "/properties/name/type: string found, array expected", …
```
=> build(deps): bump com.networknt:json-schema-validator from 1.0.87 to 1.4.3

docs/utilities/batch.md, examples/powertools-examples-batch/deploy/sqs/template.yml, examples/powertools-examples-batch/pom.xml, examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/AbstractSqsBatchHandler.java, examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/SqsBatchSender.java, examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/SqsParallelBatchHandler.java, examples/powertools-examples-batch/src/main/resources/LogLayout.json, examples/powertools-examples-batch/src/main/resources/log4j2.xml, examples/powertools-examples-cloudformation/pom.xml, pom.xml, powertools-batch/pom.xml, powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/BatchMessageHandler.java, powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/DynamoDbBatchMessageHandler.java, powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/KinesisStreamsBatchMessageHandler.java, powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/SqsBatchMessageHandler.java, powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/internal/MultiThreadMDC.java, powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/DdbBatchProcessorTest.java, powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/KinesisBatchProcessorTest.java, powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/SQSBatchProcessorTest.java, powertools-batch/src/test/resources/dynamo_event_big.json, powertools-batch/src/test/resources/kinesis_event_big.json, powertools-batch/src/test/resources/sqs_event_big.json
**Issue #, if available:** #1540
batch module can now process items in parallel rather than in sequence. Introduction of a new method `processBatchInParallel` in `BatchMessageHandler`. Works with SQS, Kinesis, DDB Streams but not SQS FIFO (does not make sense).
**Checklist**
=> feat(v2): parallel batch processing

powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/JavaRuntime.java
- removing 1.8 AL1 from E2E tests as it is deprecated
**Checklist**
=> chore: java 1.8 AL1 is deprecated, fix E2E tests

docs/core/logging.md, docs/core/metrics.md, docs/core/tracing.md, examples/powertools-examples-core/gradle/template.yaml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/JavaRuntime.java
- Remove java8 from sam examples: `Error: Building functions with java8 is no longer supported`
**Checklist**
=> chore: deprecate java1.8 al1

docs/FAQs.md, docs/roadmap.md, mkdocs.yml
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1761
**Checklist**
* [N/A] Update tests
Screenshot of rendered documentation:
=> docs: add roadmap page and include roadmap for 2025

.github/workflows/build-docs.yml, .github/workflows/dispatch_analytics.yml, .github/workflows/docs.yml, .github/workflows/pr_artifacts_size.yml, .github/workflows/pr_build.yml, .github/workflows/pr_build_v2.yml, .github/workflows/pr_iac_lint.yml, .github/workflows/publish.yml, .github/workflows/release-drafter.yml, .github/workflows/release-prep.yml, .github/workflows/run-e2e-tests-v2.yml, .github/workflows/run-e2e-tests.yml, .github/workflows/secure_workflows.yml, .github/workflows/spotbugs.yml
**Issue #, if available:** #1763
Adds root level permissions and refines permissions in workflows
**Checklist**
=> chore(ci): update permissions

examples/powertools-examples-core/cdk/infra/pom.xml
**Issue #, if available:** 
Pin JSII's jackson-databind version to 2.14
**Checklist**
=> build(deps): Fix Jackson version to max allowed by JSII

.github/workflows/publish.yml, .gitignore, tree.txt
Adds write permissions for contents and issues to release workflow
**Checklist**
=> Release permissions

examples/powertools-examples-core/cdk/infra/pom.xml, tree.txt
=> chore(deps): update JSII to 1.108

examples/powertools-examples-core/cdk/app/pom.xml, examples/powertools-examples-core/cdk/infra/pom.xml, powertools-logging/pom.xml, tree.txt
**Issue #, if available:** #1775
**Checklist**
=> chore(deps): Update deps for jackson

powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/UserAgentConfigurator.java
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1812
This PR uses `getResourceAsStream()` instead of `getResource()` to fix loading the [`version.properties`](https://github.com/aws-powertools/powertools-lambda-java/blob/8479a7f584759dd90e1106024631b6767b79bf0e/powertools-common/src/main/resources-filtered/version.properties) when Powertools is used as a dependency in a packaged JAR. `getResource()` cannot be used because files inside a JAR are no regular files. They can only be read via streams.
**Checklist**
N/A
=> fix: Load version.properties file as resource stream to fix loading when packaged as jar

docs/utilities/idempotency.md, examples/powertools-examples-idempotency/src/main/java/helloworld/App.java, powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/IdempotencyConfig.java, powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java, powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1780
This PR adds the possibility of creating a response hook in the Idempotency configuration that will be applied on all idempotent responses before returning. 
**Checklist**
N/A
=> feat(idempotency): Add response hook feature

docs/utilities/large_messages.md
Fix indentation in large messages docs for aspectj-maven-plugin
While reading the docs for the large messages utility I noticed the XML formatting was off for the maven configuration. The formatting is missing indentation. This PR tries to fix that.
**Checklist**
=> docs: Correct XML formatting for Maven configuration in Large Messages utility docs

powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/exceptions/IdempotencyItemAlreadyExistsException.java, powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java, powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DataRecord.java, powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java, powertools-idempotency/powertools-idempotency-dynamodb/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStore.java, powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBConfig.java, powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStoreTest.java, powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/IdempotencyTest.java, powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/handlers/IdempotencyFunction.java
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1784
This feature avoids redundant DynamoDB calls in the Idempotency utility by making use of the `ReturnValuesOnConditionCheckFailure` option in the AWS SDK.
Instead of re-fetching a data record from the persistence store when a `IdempotencyItemAlreadyExistsException` is thrown, it attaches the offending data record to the exception so that it can be directly returned to the caller without making another DynamoDB call. 
Note: In addition to unit tests, I ran E2E tests as well. Until E2E tests are restored in GitHub workflows, here is the output from running in my AWS account.
```
❯ mvn -Pe2e -B verify --file powertools-e2e-tests/pom.xml -Dtest="IdempotencyE2ET.java"
...
20:49:11.010 [main] INFO …
```
=> feat(idempotency): Add support for ReturnValuesOnConditionCheckFailure in Idempotency.

.github/workflows/check-e2e.yml, .github/workflows/security-dependencies-check.yml
**Issue #, if available:** #1231
- sets JAVA_VERSION env var
- sets head-ref for dependency-review
**Checklist**
=> fix(ci): minor fixes for workflows

.github/workflows/release.yml
**Issue #, if available:** #1231
adds where to look for user/pass in java setup
```
server-id: ossrh
server-username: MAVEN_USERNAME
server-password: MAVEN_PASSWORD
```
**Checklist**
=> fix(ci): Set user/pass for publishing to maven central 

powertools-logging/powertools-logging-logback/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonEncoderTest.java, powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JsonSerializer.java
**Issue #, if available:** N/A (found while working on something else)
This is a small change fixing an edge case where the JSON formatting of structured arguments in the logging module was broken. If a String contained double quotes they were not escaped leading to a broken JSON output in the Lambda logs.
**Before**
```java
LOGGER.info("Message", entry("myString", "String with \"double quotes\""));
```
**Invalid JSON (inner double quotes are not escaped)**
`jq: parse error: Invalid numeric literal at ...`
```json
{
"level": "INFO",
"message": "Message",
"cold_start": true,
"function_arn": "arn:aws:lambda:us-east-1:***:function:***",
"function_memory_size": 512,
"function_name": "***",
"function_request_id": "7e97091d-c48e-4bc2-809f-822ac34a316f",
"function_version": "$LATEST",
"service": …
```
=> fix(logging): Escape double-quotes when serializing strings into JSON.

.github/workflows/release.yml, pom.xml
**Issue #, if available:** #1857
- Migrate publishing of artifacts including SNAPSHOTS to Maven Central. OSSRH is being deprecated.
**Checklist**
=> chore(ci): Migrate publishing to Maven Central

.github/workflows/build-docs.yml, .github/workflows/release.yml, docs/overrides/main.html, mkdocs.yml
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1239
- Add versioning plugin
- Update workflows
**Checklist**
=> docs: Add versioning plugin for docs and update workflows

docs/processes/versioning.md, docs/upgrade.md
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1895
Announce deprecation of v1 in docs and update versioning policy page.
**Checklist**
=> docs: Announce deprecation of v1

powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/EmfMetricsLogger.java, powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/EmfMetricsLoggerTest.java
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1890
Flushing without metrics has unexpected behavior in the `aws-embedded-metrics` library. It prints the root-level section of the `_aws` EMF dict to STDOUT which we don't want. We want to log a simple warning only.
Before:
```json
{"Service":"payment","logStreamId":"$LATEST","functionVersion":"$LATEST","executionEnvironment":"AWS_Lambda_java11"}
```
After:
```
// No output
```
I added a unit test catching this bug.
**Note: The PMD linting about Empty Catch Blocks is expected. We don't want to bubble up EMF exceptions to the consumer because we already do our own validation.**
**Checklist**
=> fix(metrics): Do not flush when no metrics were added to avoid printing root-level _aws dict

examples/powertools-examples-core-utilities/cdk/app/pom.xml, examples/powertools-examples-core-utilities/gradle/build.gradle, examples/powertools-examples-core-utilities/kotlin/build.gradle.kts, examples/powertools-examples-core-utilities/sam-graalvm/pom.xml, examples/powertools-examples-core-utilities/sam/pom.xml, examples/powertools-examples-core-utilities/serverless/pom.xml, examples/powertools-examples-core-utilities/terraform/pom.xml, examples/powertools-examples-idempotency/pom.xml, examples/powertools-examples-kafka/events/kafka-protobuf-event.json, examples/powertools-examples-kafka/tools/pom.xml, examples/powertools-examples-kafka/tools/src/main/java/org/demo/kafka/tools/GenerateProtobufSamples.java, examples/powertools-examples-parameters/sam-graalvm/pom.xml, examples/powertools-examples-parameters/sam/pom.xml, examples/powertools-examples-serialization/pom.xml, pom.xml, powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/AbstractKafkaDeserializer.java, powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaAvroDeserializer.java, powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaJsonDeserializer.java, powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaProtobufDeserializer.java, powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/AbstractKafkaDeserializerTest.java, powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaAvroDeserializerTest.java, powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaJsonDeserializerTest.java, powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaProtobufDeserializerTest.java
**Issue #, if available:** N/A
Copy of https://github.com/aws-powertools/powertools-lambda-java/pull/1906
Thanks to @karthikpswamy for contributing this logic!
> ## Description of changes:
> 
>     * Adding support for different schema registry types (Confluent and Glue)
> 
>     * Improving the handling of message indices in protobuf data
> 
>     * Fixing deserialization logic for different schema registry formats
> 
>     * Adding appropriate tests for both Confluent and Glue schema registry scenarios
> 
> 
> Schema Registry Type Detection and Deserialization Logic:
> ### No Schema Registry Integration:
> 
>     * When KafkaEvent contains no key/value metadata
> 
>     * Uses entire byte array as raw data for deserialization
> 
>     * AWS Glue Schema Registry:
> 
> 
> ### Identified …
=> fix(kafka): Handle message indices in proto data also for Glue Schema Registry

.github/branch_protection_settings/1.x.x.json, .github/branch_protection_settings/main.json
**Issue #, if available:** #1866
Updates the branch protection rules JSON
**Checklist**
=> chore(ci): Update branch protection rules

examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json, examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json, examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json, examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json, examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json, examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
With the introduction of #1927 there are some changes with regards to the native system libraries which break the existing examples in both:
- core-utilities (sam-graalvm)
- parameters (sam-graalvm)
- Changed package name for InvocationRequest as it's now part of the `dto` sub package. 
- Added additional `tenantId` field to the InvocationRequest metadata
- Added references to the jni libraries in the correct path inside the jar 
**Issue number:** #1934
---
=> fix(examples): Fix GraalVM metadata after common runtime client changes

.github/dependabot.yml
> Please provide a summary of what's being changed
This PR adds support for new package ecosystems in dependabot, namely docker and github actions. This will ensure all gh actions are up to date and allow you to use images with sha digest in Dockerfile.
> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed
**Issue number:** #1947 
---
=> chore(ci): add new dependabot package ecosystems

examples/powertools-examples-batch/deploy/sqs/template.yml, examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/AbstractSqsBatchHandler.java
The SQS Batch example was missing `Tracing: Active` on the SQS sender. This caused no trace_id to be propagated from the sender through the chain which is why the traces were not showing up in X-RAY.
Also removed wrongly placed `@Logging` annotation.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/1994
---
=> docs(examples): Enable end to end tracing for SQS batch example.

examples/powertools-examples-core-utilities/sam-bazel/.bazelrc, examples/powertools-examples-core-utilities/sam-bazel/.gitignore, examples/powertools-examples-core-utilities/sam-bazel/BUILD.bazel, examples/powertools-examples-core-utilities/sam-bazel/MODULE.bazel, examples/powertools-examples-core-utilities/sam-bazel/README.md, examples/powertools-examples-core-utilities/sam-bazel/events/event.json, examples/powertools-examples-core-utilities/sam-bazel/src/main/java/helloworld/App.java, examples/powertools-examples-core-utilities/sam-bazel/src/main/java/helloworld/AppStream.java, examples/powertools-examples-core-utilities/sam-bazel/src/main/resources/log4j2.xml, examples/powertools-examples-core-utilities/sam-bazel/template.yaml
This PR adds a new code example `sam-bazel` showcasing how to use the Core Utilities including AspectJ compile-time weaving using Bazel.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/2021
---
=> docs(examples): Add Bazel example for core utilities

powertools-e2e-tests/pom.xml, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/MetricsE2ET.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/RetryUtils.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/metrics/MetricsFetcher.java, powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/TraceFetcher.java
This PR addresses two reliability issues of the TracingE2E tests which were failing occasionally:
1. The search horizon was too narrow. When the trace started at the end of minute x and some subsegments got populated in minute y, they were not found. I added a one minute padding to the search horizon.
2. After finding trace ids for the search, we immediately attempted to fetch the (sub-)segments of that trace without accounting for that fact that they are populated async with a delay. I added retries for the second query for the sub-segments as well. See comment https://github.com/aws-powertools/powertools-lambda-java/issues/1846#issuecomment-3160493455
Also adds some more debug logs and more useful logging statements to make debugging easier in the future.
**Issue number:** …
=> chore(ci): Improve reliability of retries in TracingE2ET

.github/workflows/security-dependencies-check.yml
This PR removes all non-PR triggers from the Verify Dependencies workflow. Those are not necessary since the main branch is protected and all checks are run (and commented by the bot) on a Pull Request.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/1909
---
=> chore(ci): Remove non-PR triggers for verify dependencies workflow.

.github/workflows/release.yml
This PR fixes a small issue where the documentation version during the release workflow was not correctly deployed. We checked out the old repository code instead of the code of the version bump PR.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/1911
---
=> chore(ci): Fix issue where docs were released with old version during release

powertools-idempotency/powertools-idempotency-dynamodb/pom.xml
This PR address a small issue where a circular dependency in Maven phases caused build issues for the idempotency utility when attempting to start dynamodb-local before unit tests on an initial `mvn -B test` command. 
The issue is:
- Maven tries to copy all artifacts to `${project.build.directory}/dynamodb-local` before running unit tests.
- However, at this time the production dependencies are not yet built (`powertools-idempotency-core`)
- Maven cannot copy the artifacts of non-built `powertools-idempotency-core` and fails
Solution:
- `powertools-idempotency-core` is not needed for DynamoDB local which is treated as an external process. Removing it solves the circular dependency.
Example failure: https://github.com/aws-powertools/powertools-lambda-java/actions/runs/17577454233/job/499259 …
=> chore(ci): Fix circular dependency in dynamodb-local and maven packaging phases

pom.xml
The publish task still fails after https://github.com/aws-powertools/powertools-lambda-java/pull/2137. We cannot have the SNAPSHOT version in the default Maven profile. 
https://github.com/aws-powertools/powertools-lambda-java/actions/runs/17581345159/job/49938824194
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/2079
---
=> chore(ci): Set mockito SNAPSHOT version only for Graal profiles.

docs/overrides/main.html
Add correct docs meta tags for AWS docs domain.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/2167
---
=> chore(docs): Add AWS docs meta tags
