- docs/content/utilities/sqs_large_message_handling.mdx
Minor syntax fixes on docs
**Checklist**
> docs: Update SQS large payload docs

- .github/workflows/build.yml
Change in root pom should also trigger build
**Checklist**
> ci: Change in root pom should also trigger build

- README.md
- docs/content/index.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
Preparing release v0.2.0-beta
**Checklist**
> ci: preparing release v0.2.0-beta

- .github/dependabot.yml
Dependabot intgeration
**Checklist**
> ci: dependabot for maven dependency upgrades

- README.md
- docs/content/index.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
> ci: preparing release v0.3.0-beta

- pom.xml
- powertools-tracing/pom.xml
Removing duplicated dependencies for X-Ray
**Checklist**
> fix: Removing v1 Java SDK dependencies for X-Ray

- pom.xml
Bump the version of payloadoffloading-common
**Checklist**
> build(deps): bump payloadoffloading-common from 1.0.0 to 1.1.0

- .github/workflows/build.yml
Will automerge PR from dependabot if all the checks pass
**Checklist**
> ci: Automerge PR from dependabot

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
> chore: Prepare for 0.5.0-beta

- README.md
Added cross-ref to Python implementation and clarified that the repo is Java-focused.
n/a
- Added cross-ref to Python repo
- Clarified Java-focus
- Added "AWS" in title
**Checklist**
> improv: tweak README.md

- README.md
- docs/content/index.mdx
> docs: Update all the environment variables used

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- docs/content/utilities/validation.mdx
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prepare for 0.6.0-beta

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- docs/content/utilities/validation.mdx
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prep for GA (1.0.0)

- docs/content/index.mdx
> doc: minor fixes

- docs/content/dummy.md
- docs/package.json
- docs/yarn.lock
> fix: fixing dependencies security issues

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- docs/content/utilities/validation.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prep for release (1.0.1)

- docs/content/index.mdx
add reference to https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java
**Checklist** 
> doc: add reference to cookiecutter-aws-sam-powertools-java

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- docs/content/utilities/validation.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prep release 1.1.0

- .github/workflows/build.yml
Modify build.yml workflow so that it will run a CI build for any change to a GitHub Action workflow
**Checklist**
> ci: add .github/workflows to CI build.yml

- README.md
- docs/content/index.mdx
- docs/content/utilities/batch.mdx
- docs/content/utilities/parameters.mdx
- docs/content/utilities/sqs_large_message_handling.mdx
- docs/content/utilities/validation.mdx
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prep release 1.2.0

- powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java
- powertools-core/src/test/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessorTest.java
> feat: respect code guru profile handler implementation

- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: Prep release 1.3.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.4.0

- .github/workflows/build.yml
> chore:  add JDK 16 to build matrix

- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
Correcting wrong version numbers for dependencies. 
Removing jcenter from the Gradle config.
**Checklist**
> Java core fix

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.6.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.7.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.7.1

- docs/core/logging.md
Fix import statements in logging docs
> Fix imports @Logging after upgrade

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.7.2

- powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java
**Issue #, if available:** #507 
**Checklist**
> fix: reset cold start only when placed on handler

- pom.xml
https://junit.org/junit5/docs/5.8.0/release-notes/
**Checklist**
> build(deps): junit 5.8.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.8.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
Release to upgrade Log4j to v1.5.0 in response to [CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)
**Checklist**
> chore: prep release 1.8.1

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
Upgrading Log4j to version 2.16.0 for [CVE-2021-45046](https://nvd.nist.gov/vuln/detail/CVE-2021-45046)
**Checklist**
> chore: prep release 1.8.2

- powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/AbstractJacksonLayoutCopy.java
- powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JacksonFactoryCopy.java
- powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonLayout.java
- spotbugs-exclude.xml
> chore: localise abstract json layout implementation

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.9.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: prep release 1.10.0

- CHANGELOG.md
- README.md
- docs/index.md
- docs/utilities/batch.md
- docs/utilities/custom_resources.md
- docs/utilities/parameters.md
- docs/utilities/sqs_large_message_handling.md
- docs/utilities/validation.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> master: Upgrading Powertool to version 1.10.1 for Log4j version upgrade

- CHANGELOG.md
- README.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-java/blob/prep-release-1.10.2/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.10.2

- CHANGELOG.md
- README.md
- example/HelloWorldFunction/build.gradle
- example/HelloWorldFunction/pom.xml
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-java/blob/prep-release-1.10.3/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.10.3

- CHANGELOG.md
- README.md
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-java/blob/prep-release-1.12.0/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.12.0

- CHANGELOG.md
- README.md
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-java/blob/prep-release-1.12.1/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.12.1

- CHANGELOG.md
- README.md
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/awslabs/aws-lambda-powertools-java/blob/prep-release-1.12.2/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.12.2

- docs/utilities/sqs_large_message_handling.md
> docs: add missing grammar article

- powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
Adding exception logging at time of capture to help make debugging/investigating issues easier through logs.
**Checklist**
> fix: Log message processing exceptions as occur

- CHANGELOG.md
- README.md
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
Release preparation: update the project version to 1.14.0
**Checklist**
> chore: update the project version to 1.14.0

- .github/workflows/build-docs.yml
- .github/workflows/docs.yml
- mkdocs.yml
**Issue #, if available:** [https://github.com/awslabs/aws-lambda-powertools-java/issues/855](url)
**Checklist**
> docs(plugin): fix mdocs and git revision plugin integration

- .github/workflows/build-docs.yml
- .github/workflows/build.yml
- .github/workflows/release-drafter.yml
- .github/workflows/spotbugs.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- mkdocs.yml
Using the `main` branch instead of the old `master`
**Checklist**
> chore: rename branch master to main

- CHANGELOG.md
- README.md
- examples/pom.xml
- examples/powertools-examples-core/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-parameters/pom.xml
- examples/powertools-examples-serialization/pom.xml
- examples/powertools-examples-sqs/pom.xml
- examples/powertools-examples-validation/pom.xml
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-e2e-tests/handlers/pom.xml
- powertools-e2e-tests/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/aws-powertools/powertools-lambda-java/blob/prep-release-1.16.0/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.16.0

- README.md
- examples/pom.xml
- examples/powertools-examples-core/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-parameters/pom.xml
- examples/powertools-examples-serialization/pom.xml
- examples/powertools-examples-sqs/pom.xml
- examples/powertools-examples-validation/pom.xml
- mkdocs.yml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-e2e-tests/handlers/pom.xml
- powertools-e2e-tests/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
Update poms to next dev version 1.17.0-SNAPSHOT
**Checklist**
> chore: update poms to next dev version 1.17.0-SNAPSHOT

- README.md
https://github.com/aws-powertools/powertools-lambda-java/issues/1286
Adding a 'how to help' section with our current customer references.
**Checklist**
> docs: adding our customer references

- examples/pom.xml
- examples/powertools-examples-cloudformation/pom.xml
- examples/powertools-examples-core/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-parameters/pom.xml
- examples/powertools-examples-serialization/pom.xml
- examples/powertools-examples-sqs/pom.xml
- examples/powertools-examples-validation/pom.xml
- pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-e2e-tests/handlers/pom.xml
- powertools-e2e-tests/pom.xml
- powertools-idempotency/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
> chore: update poms to SNAPSHOT version for dev

- examples/pom.xml
- examples/powertools-examples-batch/pom.xml
- examples/powertools-examples-cloudformation/pom.xml
- examples/powertools-examples-core/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-parameters/pom.xml
- examples/powertools-examples-serialization/pom.xml
- examples/powertools-examples-validation/pom.xml
- pom.xml
- powertools-batch/pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-e2e-tests/handlers/pom.xml
- powertools-e2e-tests/pom.xml
- powertools-idempotency/pom.xml
- powertools-large-messages/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
POMs in v2 should be 2.0.0-SNAPSHOT. 
**Checklist**
> chore: v2 - fix version

- examples/powertools-examples-batch/pom.xml
- examples/powertools-examples-cloudformation/pom.xml
- examples/powertools-examples-core/cdk/app/pom.xml
- examples/powertools-examples-core/sam/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-sqs/pom.xml
- powertools-e2e-tests/handlers/pom.xml
> fix: Roll log4j shade transformer forwards

- CHANGELOG.md
- examples/pom.xml
- examples/powertools-examples-batch/pom.xml
- examples/powertools-examples-cloudformation/pom.xml
- examples/powertools-examples-core/cdk/infra/pom.xml
- examples/powertools-examples-core/sam/pom.xml
- examples/powertools-examples-idempotency/pom.xml
- examples/powertools-examples-parameters/pom.xml
- examples/powertools-examples-serialization/pom.xml
- examples/powertools-examples-sqs/pom.xml
- examples/powertools-examples-validation/pom.xml
- pom.xml
- powertools-batch/pom.xml
- powertools-cloudformation/pom.xml
- powertools-core/pom.xml
- powertools-e2e-tests/handlers/pom.xml
- powertools-e2e-tests/pom.xml
- powertools-idempotency/pom.xml
- powertools-large-messages/pom.xml
- powertools-logging/pom.xml
- powertools-metrics/pom.xml
- powertools-parameters/pom.xml
- powertools-serialization/pom.xml
- powertools-sqs/pom.xml
- powertools-test-suite/pom.xml
- powertools-tracing/pom.xml
- powertools-validation/pom.xml
This is automated release prep. Remember to update [CHANGELOG.md](https://github.com/aws-powertools/powertools-lambda-java/blob/prep-release-1.17.0/CHANGELOG.md) to capture changes in this release. Please review changes carefully before merging.
> chore:Prep release 1.17.0

- README.md
- mkdocs.yml
Missed mkdocs and README changes v 1.17.0.
**Checklist**
> chore: Fix missing version change pieces

- powertools-batch/pom.xml
Module title and description are missing from the powertools-batch library. Fix this. 
**Checklist**
> chore: Clean up batch POM

- README.md
https://github.com/aws-powertools/powertools-lambda-python/issues/3207
**Checklist**
>  docs(customer-reference): add Vertex Pharmaceuticals as a customer reference

- .github/workflows/pr_artifacts_size.yml
- examples/powertools-examples-idempotency/pom.xml
- powertools-idempotency/pom.xml
fix the branch name and add v2 + missing modules
**Checklist**
> chore: artifacts size on good branches

- .github/workflows/pr_artifacts_size.yml
- README.md
- examples/powertools-examples-idempotency/pom.xml
- powertools-idempotency/pom.xml
- powertools-serialization/pom.xml
merge main into v2
**Checklist**
> chore: merge main into v2

- docs/index.md
- powertools-e2e-tests/handlers/pom.xml
version 1.9.21 of aspectj has been released (see [issue](https://github.com/eclipse-aspectj/aspectj/issues/260#issuecomment-1849301573)) ==> removing M1
**Checklist**
* [] Update tests
> build(deps): bump aspectj to 1.9.21 for jdk21

- README.md
n/a
Update readme to reflect current status of v2 branch and appropriate quality links.
**Checklist**
> docs(v2): Update README.md

- .github/workflows/pr_iac_lint.yml
Fix PR lint issues.
**Checklist**
> chore(v2): Fix build

- .github/workflows/pr_iac_lint.yml
> chore(v2): Fix IaC lint

- docs/core/tracing.md
Fix links to XRay in tracing documentation.
**Checklist**
> docs: fix tracing links for xray

- docs/core/tracing.md
Improved documentation on SDK instrumentation with X-RAY.
**Checklist**
> docs: improve tracing doc for sdk instrumentation

- .github/workflows/release-prep.yml
> chore(ci): Remove RELEASE variable

- .github/workflows/pr_build.yml
**Issue #, if available:** #1775
**Checklist**
> fix(ci): Add workflow_dispatch to build script

- .github/workflows/release-drafter.yml
**Issue #, if available:** #1770
**Checklist**
> chore(ci): Update release-drafter.yml

- .gitignore
- docs/processes/versioning.md
- docs/requirements.in
- docs/requirements.txt
- docs/roadmap.md
- docs/utilities/validation.md
- mkdocs.yml
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1760, https://github.com/aws-powertools/powertools-lambda-java/issues/1804
**Preview link:** https://dealn7fl31ram.cloudfront.net/
- Create Versioning Policy page in preparation for `v2` release (#1804)
- Note: The upgrade guide will be published on the preview docs as part of a separate PR
- Update Roadmap with current progress
- Add llms.txt
- Enable `privacy` plugin (#1760)
- Formatting fixes on Validation page
**Checklist**
> docs: Add version policy page and llms.txt, enable privacy plugin, fix formatting

- .github/workflows/release.yml
**Issue #, if available:** #1231
Adds better control flow for when things are skipped
**Checklist**
> fix(ci): Update control flow to allow for better skipping of things

- .github/workflows/release.yml
**Issue #, if available:** https://github.com/aws-powertools/powertools-lambda-java/issues/1870
**Checklist**
> fix(ci): Checkout repo on doc release

- .github/branch_protection_settings/main.json
> Please provide a summary of what's being changed
Updates the main branch output for branch protection
> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed
**Issue number:** 2052
---
> fix(ci): Update branch protection output

- mkdocs.yml
Updates AWS copyright notice in documentation footer inline with AWS standards.
**Issue number:** https://github.com/aws-powertools/powertools-lambda-java/issues/2118
---
> docs: Update AWS copyright notice
